name: Sync Hugging Face to GitHub

on:
  schedule:
    - cron: "0 0 * * *" # 每天同步一次
  workflow_dispatch: # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Download Hugging Face repository
        run: |
          pip install huggingface_hub
          huggingface-cli download your-username/your-repo --local-dir ./your-repo

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Sync from Hugging Face"
          git push
