name: Sync Hugging Face to GitHub

on:
  workflow_dispatch: # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Download Hugging Face repository
        run: |
          pip install huggingface_hub
          huggingface-cli download AntonCook/dypromotion --local-dir ./dypromotion

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Sync from Hugging Face"
          git push
